[Installation]: Avoid ModuleNotFound:setuptools-scm error (#476)
Current instructions for setup using standalone docker (not using
Dockerfile) is missing the pip install -r requirements-hpu.txt
instruction. A new user using this method for setup will encounter :

```
File "/root/vllm/setup.py", line 15, in <module>
    from setuptools_scm import get_version
ModuleNotFoundError: No module named 'setuptools_scm'
```
This PR fixes that.